// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/avatars": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Avatars"
                ],
                "summary": "Avatarsを全件取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Avatar"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Avatars"
                ],
                "summary": "Avatarを一件登録する",
                "parameters": [
                    {
                        "description": "Avatar",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.Avatar"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登録したAvatar",
                        "schema": {
                            "$ref": "#/definitions/model.Avatar"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/avatars/between-time": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Avatars"
                ],
                "summary": "更新日時がfrom, toの間のAvatarを返す",
                "parameters": [
                    {
                        "type": "string",
                        "description": "2022-11-27 0:00:00",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "2022-11-28 0:00:00",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Avatar"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/avatars/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Avatars"
                ],
                "summary": "avatarIdで検索したAvatarを1件返す",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アバターID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Avatar"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Avatars"
                ],
                "summary": "avatarIdで指定したAvatarを1件削除する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アバターID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/complaints": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Complaints"
                ],
                "summary": "Complaintsを全件取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Complaint"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Complaints"
                ],
                "summary": "Complaintを一件登録する",
                "parameters": [
                    {
                        "description": "Complaint",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.Complaint"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登録したComplaint",
                        "schema": {
                            "$ref": "#/definitions/model.Complaint"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/complaints/between-time": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Complaints"
                ],
                "summary": "更新日時がfrom, toの間のComplaintを返す",
                "parameters": [
                    {
                        "type": "string",
                        "description": "2022-11-27 0:00:00",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "2022-11-28 0:00:00",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Complaint"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/complaints/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Complaints"
                ],
                "summary": "avatarIdで検索したComplaintを1件返す",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アバターID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Complaint"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Complaints"
                ],
                "summary": "complaintIdで指定したComplaintを1件削除する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "愚痴ID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Avatar": {
            "type": "object",
            "properties": {
                "avatarId": {
                    "type": "integer",
                    "example": 1234567890
                },
                "avatarName": {
                    "type": "string",
                    "example": "Nino"
                },
                "avatarText": {
                    "type": "string",
                    "example": "なのよ"
                },
                "imageUrl": {
                    "type": "string",
                    "example": "https://hoge.com/fuga"
                }
            }
        },
        "model.Complaint": {
            "type": "object",
            "properties": {
                "avatarId": {
                    "type": "string",
                    "example": "1"
                },
                "complaintId": {
                    "description": "ID, CreatedAt, UpdatedAt, DeletedAt が付与される\n=\u003e Error 1054: Unknown column 'created_at' in 'field list'のエラー\ngorm.Model\nタグ` + "`" + `gorm:\"primaryKey\"` + "`" + `を付与。goの構造体は、複数のタグがある場合は半角スペースで区切って記載",
                    "type": "integer",
                    "example": 56
                },
                "complaintText": {
                    "type": "string",
                    "example": "勘弁してくれ!"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "gin-swagger guchitter",
	Description:      "はじめてのswagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
