// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/complaints": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Complaints"
                ],
                "summary": "Complaintsを全件取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Complaint"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Complaints"
                ],
                "summary": "Complaintを一件登録する",
                "parameters": [
                    {
                        "description": "Complaint",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.Complaint"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登録したComplaint",
                        "schema": {
                            "$ref": "#/definitions/model.Complaint"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/complaints/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Complaints"
                ],
                "summary": "avatarIdで検索したComplaintを1件返す",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アバターID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Complaint"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Complaint": {
            "type": "object",
            "properties": {
                "avatarId": {
                    "type": "string",
                    "example": "1"
                },
                "complaintText": {
                    "type": "string",
                    "example": "勘弁してくれ!"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "gin-swagger guchitter",
	Description:      "はじめてのswagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
