definitions:
  model.Complaint:
    properties:
      avatarId:
        example: "1"
        type: string
      complaintText:
        example: 勘弁してくれ!
        type: string
    type: object
info:
  contact: {}
  description: はじめてのswagger
  title: gin-swagger guchitter
  version: 0.0.1
paths:
  /complaints:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Complaint'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Complaintsを全件取得
      tags:
      - Complaints
    post:
      parameters:
      - description: Complaint
        in: body
        name: body
        schema:
          $ref: '#/definitions/model.Complaint'
      produces:
      - application/json
      responses:
        "200":
          description: 登録したComplaint
          schema:
            $ref: '#/definitions/model.Complaint'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Complaintを一件登録する
      tags:
      - Complaints
  /complaints/{id}:
    get:
      parameters:
      - description: アバターID
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Complaint'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: avatarIdで検索したComplaintを1件返す
      tags:
      - Complaints
swagger: "2.0"
